### ISSUE TITLE
Setting strict true in `tsconfig.json` results in TS error

### ISSUE THREAD

**Issue by nooblyf** [neondatabase/serverless#66] opened 2024-02-29 19:17 UTC
## Steps to reproduce
Set `strict` in tsconfig to `true`

Connect
```ts
import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";

import { DATABASE_URL } from "$env/static/private";

const sql = neon(DATABASE_URL);
export const DB = drizzle(sql);
```

## Expected result
No TS error

## Actual result
TS error:
<img width="865" alt="Screenshot 2024-03-01 at 00 39 39" src="https://github.com/neondatabase/serverless/assets/54323745/ef63b75c-0c42-48fb-b9a2-daaaf1812b0b">

## Environment
typescript v5.3.3
@sveltejs/kit v2.5.2
node v20.10.0
pnpm 8.11.0

## Logs, links
```txt
Argument of type 'NeonQueryFunction<false, false>' is not assignable to parameter of type 'NeonQueryFunction<boolean, boolean>'.
  Types of property 'transaction' are incompatible.
    Type '<ArrayModeOverride extends boolean = false, FullResultsOverride extends boolean = false>(queriesOrFn: NeonQueryPromise<false, false, any>[] | ((sql: NeonQueryFunctionInTransaction<ArrayModeOverride, FullResultsOverride>) => NeonQueryInTransaction[]), opts?: HTTPTransactionOptions<...> | undefined) => Promise<...>' is not assignable to type '<ArrayModeOverride extends boolean = boolean, FullResultsOverride extends boolean = boolean>(queriesOrFn: NeonQueryPromise<boolean, boolean, any>[] | ((sql: NeonQueryFunctionInTransaction<ArrayModeOverride, FullResultsOverride>) => NeonQueryInTransaction[]), opts?: HTTPTransactionOptions<...> | undefined) => Promise...'.
      Types of parameters 'queriesOrFn' and 'queriesOrFn' are incompatible.
        Type '((sql: NeonQueryFunctionInTransaction<any, any>) => NeonQueryInTransaction[]) | NeonQueryPromise<boolean, boolean, any>[]' is not assignable to type '((sql: NeonQueryFunctionInTransaction<any, any>) => NeonQueryInTransaction[]) | NeonQueryPromise<false, false, any>[]'.
          Type 'NeonQueryPromise<boolean, boolean, any>[]' is not assignable to type '((sql: NeonQueryFunctionInTransaction<any, any>) => NeonQueryInTransaction[]) | NeonQueryPromise<false, false, any>[]'.
            Type 'NeonQueryPromise<boolean, boolean, any>[]' is not assignable to type 'NeonQueryPromise<false, false, any>[]'.
              Type 'NeonQueryPromise<boolean, boolean, any>' is not assignable to type 'NeonQueryPromise<false, false, any>'.
                Type 'boolean' is not assignable to type 'false'.ts(2345)
```

**Comment by jawj** [comment] 2024-03-01 12:54
Thanks for letting us know. We (and drizzle) are investigating.

**Comment by ricaringa** [comment] 2024-03-08 03:58
@jawj any news on this? I just got started with drizzle and got stuck with this.

**Comment by araf821** [comment] 2024-03-08 08:27
Downgrading to `"drizzle-orm": "^0.28.6"` solved the issue for me.

**Comment by jawj** [comment] 2024-03-08 12:22
Sorry for the delay. The drizzle guys say they hope to fix it this weekend.

**Comment by bricesuazo** [comment] 2024-03-09 15:08
Adding `NeonQueryFunction<boolean, boolean>` to sql seems to fix the typescript error.

```
import { neon } from "@neondatabase/serverless";
import type { NeonQueryFunction } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";

const sql: NeonQueryFunction<boolean, boolean> = neon(DATABASE_URL);

export const DB = drizzle(sql);
```

**Comment by jawj** [comment] 2024-03-19 07:52
I'm told that drizzle 0.30.3 fixes this problem. I'll close this issue if someone can confirm.

Sorry again that this has taken a while.

**Comment by bricesuazo** [comment] 2024-03-19 10:40
I can confirm this is fixed in `"drizzle-orm": "0.30.3"`

**Comment by jawj** [comment] 2024-03-19 10:59
Many thanks.

**Closed** 2024-03-19 10:59 UTC

**Comment by fisenkodv** [comment] 2024-11-10 06:31
The issue is reproducible in `"drizzle-orm": "0.36.1"`, `"@neondatabase/serverless": "0.10.3"`

Example from here https://orm.drizzle.team/docs/tutorials/drizzle-with-neon#connect-drizzle-orm-to-your-database
```ts
import { drizzle } from 'drizzle-orm/neon-http';
import { neon } from '@neondatabase/serverless';
import { config } from 'dotenv';

config({ path: '.env' }); // or .env.local

const sql = neon(process.env.DATABASE_URL!);

export const db = drizzle({ client: sql });
```

build fails with the following error
```
build: ./db/db.ts:9:27
build: Type error: Argument of type '{ client: NeonQueryFunction<false, false>; }' is not assignable to parameter of type '"Please install `@neondatabase/serverless` to allow Drizzle ORM to connect to the database"'.
build:
build:    7 | const sql = neon(process.env.DATABASE_URL!);
build:    8 |
build: >  9 | export const db = drizzle({ client: sql });
build:      |                           ^
build:   10 |
```
